import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Nav from "./Component/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex ">
        <div className="w-64 h-screen bg-blue-100  border-r border-gray-200 p-6">
          <h1 className="text-2xl text-black font-bold mb-8">
            🎬 Movie Collection
          </h1>
          <Nav />
        </div>
        {<div className="w-full">{children}</div>}
      </body>
    </html>
  );
}
